import Head from "next/head";
import { getSession } from "next-auth/client";
import Header from "../components/Header";
import Login from "../components/Login";
import Sidebar from "../components/Sidebar";
import Feed from "../components/Feed";
import Widgets from "../components/Widgets";
import { db } from "../firebase";

export default function Home({ session, posts }) {
  if (!session) return <Login></Login>;
  return (
    <div>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>

      <main className="flex">
        <Sidebar></Sidebar>
        <Feed posts={posts}> </Feed>
        <Widgets></Widgets>
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  //Get The User
  const session = await getSession(context);

  const posts = await db
    .collection("posts")
    .orderBy("timestamps", "desc")
    .get();

  const docs = posts.docs.map((post) => ({
    id: post.id,
    ...post.data(),
    timestamps: null,
  }));

  return {
    props: {
      session,
      posts: docs,
    },
  };
}
